### ISSUE TITLE
2023 and 2024 data?

### ISSUE THREAD

**Issue by mattwelke** [schoolofcities/bike-share-toronto#8]
Cool site! I was looking for up to date data in a nice form to show the increase in Bike Share Toronto usage. This is the best I've seen so far. But it only goes up to 2022 so far. Any plans to add 2023 and 2024 data?

**Comment by jamaps** [comment]
Thanks @mattwelke - yup I'd like to update it sometime before the end of the year - the City's open data website now has data up to 06/2024, so we can at least show data up until then

**Comment by jamaps** [comment]
Updated recently to Sept 2024
